version: "3.9"

services:
    django:
      build: .
      image: ecommerce
      container_name: ecommerce
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code/ecommerce/
      ports:
        - "8000:8000"
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
      depends_on:
        - redis
    celery:
      build: .
      command: celery -A ecommerce worker -l INFO
      volumes:
        - .:/code/ecommerce/
      depends_on:
        - django
        - redis
      environment:
        - DEBUG=1
        - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
        - CELERY_BROKER=redis://redis:6379/0
        - CELERY_BACKEND=redis://redis:6379/0
    redis:
      image: 'redis:alpine'




