# Generated by Django 3.2.3 on 2021-05-31 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Список пользователей',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название категории')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продавец',
                'verbose_name_plural': 'Продавцы',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TicketService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Цена')),
                ('term_days', models.PositiveIntegerField(verbose_name='Срок выполнения')),
                ('warranty_days', models.PositiveIntegerField(verbose_name='Гарантийный срок')),
                ('category', models.ManyToManyField(related_name='TicketServices', to='main.Category', verbose_name='Категория')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ticketservice_related', to='main.seller', verbose_name='Продавец')),
                ('tag', models.ManyToManyField(related_name='main_ticketservice_related', to='main.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Объявление - услуги',
                'verbose_name_plural': 'Объявления - услуги',
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Цена')),
                ('state', models.CharField(choices=[('new', 'новое'), ('used', 'б/у')], max_length=10, verbose_name='Состояние')),
                ('qty', models.PositiveIntegerField(verbose_name='Количество')),
                ('category', models.ManyToManyField(related_name='TicketItems', to='main.Category', verbose_name='Категория')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ticketitem_related', to='main.seller', verbose_name='Продавец')),
                ('tag', models.ManyToManyField(related_name='main_ticketitem_related', to='main.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Объявление - вещи',
                'verbose_name_plural': 'Объявления - вещи',
            },
        ),
        migrations.CreateModel(
            name='TicketCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Название')),
                ('text', models.CharField(max_length=200, verbose_name='Текст')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField()),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Цена')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=10, verbose_name='Цвет')),
                ('category', models.ManyToManyField(related_name='TicketCars', to='main.Category', verbose_name='Категория')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ticketcar_related', to='main.seller', verbose_name='Продавец')),
                ('tag', models.ManyToManyField(related_name='main_ticketcar_related', to='main.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Объявление - авто',
                'verbose_name_plural': 'Объявления - авто',
            },
        ),
    ]
