# Generated by Django 3.2.3 on 2021-05-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCarArchive',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Архив - Авто ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.ticketcar',),
        ),
        migrations.CreateModel(
            name='TicketItemArchive',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Архив - Вещи',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.ticketitem',),
        ),
        migrations.CreateModel(
            name='TicketServiceArchive',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Архив - Услуги',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.ticketservice',),
        ),
        migrations.AlterField(
            model_name='ticketcar',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ticketcar_seller', related_query_name='main_ticketcar_seller', to='main.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='ticketcar',
            name='tag',
            field=models.ManyToManyField(related_name='main_ticketcar_tag', related_query_name='main_ticketcar_tag', to='main.Tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ticketitem_seller', related_query_name='main_ticketitem_seller', to='main.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='ticketitem',
            name='tag',
            field=models.ManyToManyField(related_name='main_ticketitem_tag', related_query_name='main_ticketitem_tag', to='main.Tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='ticketservice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_ticketservice_seller', related_query_name='main_ticketservice_seller', to='main.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='ticketservice',
            name='tag',
            field=models.ManyToManyField(related_name='main_ticketservice_tag', related_query_name='main_ticketservice_tag', to='main.Tag', verbose_name='Тег'),
        ),
    ]
