# Generated by Django 3.2.3 on 2021-05-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('-date_modified',), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Текст'),
        ),
    ]
