# Generated by Django 3.2.3 on 2021-05-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210529_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
