# Generated by Django 3.2.3 on 2021-06-08 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210607_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.customuser')),
                ('birth_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            bases=('main.customuser',),
        ),
    ]
