# Generated by Django 3.2.3 on 2021-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210609_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default_ava.png', upload_to='avatars'),
        ),
    ]
