# Generated by Django 3.2.3 on 2021-06-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписка активна'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='main.profile', verbose_name='Подписчик'),
        ),
    ]
