# Generated by Django 3.2.3 on 2021-07-14 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_subscriber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcar',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
        migrations.AddField(
            model_name='ticketitem',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
        migrations.AddField(
            model_name='ticketservice',
            name='is_sold',
            field=models.BooleanField(default=False, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='main.customuser'),
        ),
    ]
